### ISSUE TITLE
Whenever a new build is created, everybody's ODBC password is changed

### ISSUE THREAD

**Issue by jajwilson** [ox-it/ords#760]
This is going to cause a lot of confusion and anguished. Would it be possible for people's existing ODBC passwords and IP addresses to be retained when a new build is built?

**Comment by thestoat** [comment]
This should only happen once (when the retrofit is not run). Are you saying it happens with every new build?

**Comment by jajwilson** [comment]
That certainly seems to be true whenever there is a new build to staging I have to reset my password (to what it already was).

**Comment by thestoat** [comment]
I have just tried this on Dev. At some stage during the Project Node build, ODBC passwords were indeed reset.

**Comment by thestoat** [comment]
Running a build without the tests stops the passwords from being reset. I suspect it is the retrofit tests that make this problem happen.

I am requesting tests are switched off when building for Staging (or App) since those tests might destroy data (they should not do - but tests should not be run against production databases anyway).

**Comment by thestoat** [comment]
Ok - it was retrofit. All should be well from the next build

**Comment by thestoat** [comment]
Assigning this to Meriel since James has left

**Comment by MerielP** [comment]
I'm afraid I just had to reset my password in order to establish an ODBC connection on Dev. I can't say for certain whether this was related to a new build or to something else, though - is there any way to tell? What else might have caused me to need to reset my password?

**Comment by thestoat** [comment]
Hmmm. Love those sorts of problems. I just set my password, checked I could access a db via odbc, ran a full build and re-checked. All well. So I have written a cron script to check every hour and log the result. Will check that periodically to see if I can see a problem appear.

**Comment by thestoat** [comment]
One day and several builds on, checking every hour, the problem has not yet happened for me.

**Comment by thestoat** [comment]
2 days later the problem still hasn't happened. Please provide access to an ODBC enabled database that you are using a lot (preferably on Dev) - maybe one of your actions is causing this, so I shall set monitoring to that database also

**Comment by MerielP** [comment]
I've managed to establish an ODBC connection today, without needing to reset my password, despite there having been new builds since I last did this. So it looks as though whatever caused the problem I had earlier in the week wasn't the new build issue.

If it's still useful to monitor it to see what else might be happening, one of my standard databases for testing is 'Club membership database' in 'Victorian Gentlemen's Clubs' on Dev.

**Comment by thestoat** [comment]
My monitoring has lasted for 6 days so far - and still no problems. I have just added your database to the monitoring - let's see what happens :-) Please feel free to use that database as much as you like ...

**Comment by thestoat** [comment]
Still no problems on either database ...

**Comment by thestoat** [comment]
Still working fine

**Comment by thestoat** [comment]
It has been three weeks now with no problem with passwords. How would you like to proceed?

**Comment by MerielP** [comment]
As it's been some time since we've seen any password problems, I think we can close this. It's something else to double check when we next do a new build to Staging, but new builds on Dev certainly seem to be fine.
