### ISSUE TITLE
The first time that a user clicks 'make this the main database', it doesn't. The second time, it does.

### ISSUE THREAD

**Issue by jajwilson** [ox-it/ords#775]
1. Create a test version of your main database
2. Delete the first few records in the test database
3. Click the 'make this the main database' button under the test database section
4. Look at the main version of the database and observe that it hasn't been updated with the changes on the test version
5. Click the 'make this the main database' button under the test database section a second time
6. Observer that now the main database has indeed been updated with the changes in the test version

This shouldn't require two clicks! The test version should be copied to the main version the first time it's done.

This is happening in App 1.0.16 - 4537. I'll try Dev in a second.

**Comment by jajwilson** [comment]
Right. I'm not getting this bug in Dev (1.0.26 - 5492), but I am in staging (1.0.26 - 5474). What on earth is going on? Is this a server set-up issue?

**Comment by jajwilson** [comment]
Or I suppose it may have been 'accidentally' fixed by some other recent changes in Dev - Dave, is this a realistic possibility?

**Comment by thestoat** [comment]
I have just tried this on Staging exactly as you describe but do not see the problem. The problem also doesn't happen on Dev, as you correctly point out.

I can believe the problem happened on App but not Staging since some changes have gone in to Staging since then but I don't remember fixing anything in Dev that is currently not in Staging. If you can reproduce this issue on staging then please send me the offending database and I shall see what is going on.

**Comment by jajwilson** [comment]
How strange - you're quite right, I can't now reproduce the bug, although I swear it was in staging the other day. I've tried in both an old (pre-ODBC) database and a brand new one. Oh well, it's gone, and that's the important thing.
