### ISSUE TITLE
Can't add new tables when using Chrome

### ISSUE THREAD

**Issue by MerielP** [ox-it/ords#784]
When using Chrome, if I go into the schema designer and try to add a new table, I can't. After I click the 'Add table' button, the mouse pointer turns to a cross (as it should), but nothing happens when I click the working area.

I'm using Chrome version 49.0.2623.110 m (which it tells me is up to date) on Windows 7.

Adding new tables still seems to work OK in Firefox.

**Comment by thestoat** [comment]
You are so lucky to get that far. When I use Chrome on the Dev servers I get ...

Bad Request

Your browser sent a request that this server could not understand.
Size of a request header field exceeds server limit.
Cookie
/n
... on Mac. Sometimes Linux, too. Using Chrome on Staging works for me (which is to say it is pretty badly broken, but not in this way, and SysDave has been informed.

Using Chrome on Dev on Linux works (with the aforementioned caveat that performance is sometimes abysmal and can time out). Using Chrome on Dev on Windows 10 also works (with the same caveat). Are you able to try on a different W7 machine? Are you also able to try on a W10 machine? I need to ascertain the extent of the problem.

**Comment by MerielP** [comment]
I've just tried this again on Dev, and adding new tables now seems to be working fine on both Chrome and Firefox. I also brought my own Windows 10 machine in today, and have tested it there (also on both Chrome and Firefox), and again, it seems fine.

So this seems to have passed into the realms of annoying intermittent bugs that we can't reproduce later. Is there anything else that needs doing about this, or do we just resolve it and hope for the best? (And is there anything else that needs doing about the problems using Chrome you mention above?)

**Comment by thestoat** [comment]
You hadn't mentioned initially if the problem was Dev or Staging, though your most recent comment suggests you found the problem on Dev. Since neither of us can reproduce the issue I think the only thing for it is to close it for now - and re-raise if it happens again. 

As for the performance problems, I have spoken to SysDave and will provide him with the time it happens next - if it does happen again - so he can check logs.

The Chrome issue has happened to me before and tends to vanish of its own accord but I shall raise an issue about it with SysDev when I next see the issue, in case they can see any problems in the logs ...

**Comment by MerielP** [comment]
I think the initial problem was on Dev. To be on the safe side, I've just tested it on Staging, and all seems well there, too. So I'll close this issue.
