### ISSUE TITLE
Database in live project seems to have stuck part of the way through the upload process

### ISSUE THREAD

**Issue by MerielP** [ox-it/ords#789]
The same researcher mentioned in issue #788 also has a problem with another database: the upload process seems to have stalled part of the way through.

Details of this problem also sent privately via email.

**Comment by thestoat** [comment]
I have looked in to this. There are three databases on App (out of 181) where the import status is flagged as "in progress", this being one of them. The database does not exist on the server so this is a state that should not happen, and is obviously hard to reproduce. My guess is some network or server error (the same that caused 788) caused this problem too.

The code should recover from this but I do see a problem where it won't check for these databases so I shall fix this for future imports now. It won't work on the current databases in app since they have been deleted.

**Comment by thestoat** [comment]
Fixed
